steps:
  # 0. Crear directorios destino (gsutil falla si no existen)
  - name: 'ubuntu'
    args: ['bash', '-c', 'mkdir -p ./data/chroma_db ./rr_model']
    id: 'create-dirs'

  # 1. Descargar artefactos desde GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'gs://${_BUCKET_NAME}/chroma_db', './data/']
    id: 'download-chroma-db'
    waitFor: ['create-dirs']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'gs://${_BUCKET_NAME}/rr_model', './rr_model']
    id: 'download-rr-model'
    waitFor: ['create-dirs']

  # 2. Construir imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cosora-demo', '-f', 'deploy/Dockerfile', '.']
    id: 'build-docker-image'
    waitFor: ['download-chroma-db', 'download-rr-model']

  # 3. Subir la imagen Docker al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cosora-demo']
    id: 'push-docker-image'
    waitFor: ['build-docker-image']

# Definimos que el servicio usará la variable externa _BUCKET_NAME
substitutions:
  _BUCKET_NAME: 'rag-actas-db-bucket' # Valor por defecto, se puede sobrescribir al lanzar build

options:
  logging: CLOUD_LOGGING_ONLY
